web:
  build: .
  volumes:
    - .:/imgupl
  environment:
    DATABASE_DB: imgupl
    DATABASE_HOST: db
    DATABASE_USER: postgres
    SECRET_KEY_BASE: 87e20525ce88da831824af93fdc1ccd124e73378d5490adbc09690a713b41dda4ac1e9b640e6125145342213e36a4c3ae779fc7a499a3516e965f9a37057e45a
    SMTP_HOST: mail
    SMTP_PORT: 1025
  ports:
    - "3000:3000"
  links:
    - db
    - mail
db:
  image: postgres
  expose:
    - "5432"
mail:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"
  expose:
    - "1025"
