version: '2'

services:
  web:
    build: .
    volumes:
      - .:/imgupl
    environment:
      DATABASE_DB: imgupl
      DATABASE_HOST: db
      DATABASE_USER: postgres
      SECRET_KEY_BASE: foobar
      SMTP_HOST: mail
      SMTP_PORT: 1025
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mail

  db:
    image: postgres

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
