default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DATABASE_CONNECTION_POOL', 5) %>
<% if ENV['DATABASE_HOST'] %>
  host: <%= ENV['DATABASE_HOST'] %>
<% end %>
<% if ENV['DATABASE_PORT'] %>
  port: <%= ENV['DATABASE_PORT'].to_i %>
<% end %>
<% if ENV['DATABASE_USER'] %>
  username: '<%= ENV['DATABASE_USER'] %>'
<% end %>
<% if ENV['DATABASE_PASSWORD'] %>
  password: '<%= ENV['DATABASE_PASSWORD'] %>'
<% end %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_DB') %>_development

test: &test
  <<: *default
  database: <%= ENV.fetch('DATABASE_DB') %>_test

cucumber:
  <<: *test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_DB') %>
